# Generated by Django 4.2.1 on 2023-05-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_image_1', models.ImageField(upload_to='')),
                ('stream_image_2', models.ImageField(upload_to='')),
            ],
        ),
    ]
