# Generated by Django 4.2.1 on 2023-05-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='stream_image_1',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='stream_image_2',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
